name: 'Hello World'
description: 'saying hello world to composite action'
inputs:
  your-name:    # id of input
    description: 'Your name'
    required: true
    default: 'ODNMAN'

runs:
  using: composite
  steps:
    - run: echo Hello ${{ inputs.your_name }}.
      shell: bash
    - run: ${{github.action_path }}/helloworld.sh
      shell: bash